name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels:
       - feature
       - enhancement
  - title: 🐛 Bug Fixes
    labels:
       - fix
       - hotfix
       - bug
  - title: 🧰 Maintenance
    labels:
       - chore
       - ci
       - workflow
       - tests
       - maintenance
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
