site_name: Magic Areas
docs_dir: source
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    #- toc.integrate
    - toc.follow
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  palette:
    - schema: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep-purple
      accent: amber
    - scheme: slate
      primary: deep-purple
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: https://raw.githubusercontent.com/home-assistant/brands/master/custom_integrations/magic_areas/logo.png
  favicon: https://brands.home-assistant.io/_/magic_areas/dark_icon.png
extra:
  generator: false
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Concepts:
      - Overview: concepts/index.md
      - Presence Sensing: concepts/presence-sensing.md
      - Area States: concepts/area-states.md
      - Meta-Areas: concepts/meta-areas.md
  - How-To:
      - Installation: how-to/installation.md
      - Getting Started: how-to/getting-started.md
      - Troubleshooting: how-to/troubleshooting.md
      - Library:
        - Overview: how-to/library/index.md
        - Making every room magic: how-to/library/making-every-room-magic.md
        - Using energy aggregates on the energy dashboard: how-to/library/energy-aggregates.md
        - Automatic lights brightness control: how-to/library/automatic-light-brightness-control.md
        - Set-and-forget home alarm with Alarmo: how-to/library/integrating-with-alarmo.md
        - Perfecting climate comfort with Climate Control: how-to/library/perfecting-climate-comfort.md
  - Features:
      - Overview: features/index.md
      - Smart Groups:
          - Light Groups: features/light-groups.md
          - Fan Groups: features/fan-groups.md
          - Climate Control: features/climate-control.md
      - Simple Groups:
          - Cover Groups: features/cover-groups.md
          - Media Player Groups: features/media-player-groups.md
      - Sensors & Tracking:
          - Aggregation: features/aggregation.md
          - Health Sensors: features/health-sensor.md
          - BLE Tracker Monitor: features/ble-tracker-monitor.md
          - Wasp in a Box: features/wasp-in-a-box.md
      - Utilities:
          - Area-Aware Media Player: features/area-aware-media-player.md
          - Presence Hold: features/presence-hold.md
  - Community: community.md


repo_url: https://github.com/jseidl/magic-areas
edit_uri: blob/main/docs/source/
site_url: https://magicareas.io
