name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  ruff:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v5"

        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements-test.txt

        - name: Get latest HA stable version from PyPI
          run: |
            VERSIONS=$(curl -s https://pypi.org/pypi/homeassistant/json | jq -r '.releases | keys | .[]')
            STABLE=$(echo "$VERSIONS" | grep -Ev '[a-zA-Z]' | sort -Vr | head -n1)
            echo "HA_VERSION=$STABLE" >> $GITHUB_ENV

        - name: "Run"
          run: tox -e lint
