name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.0"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/magic_areas/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/magic_areas"
          zip magic_areas.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ${{ github.workspace }}/custom_components/magic_areas/magic_areas.zip
