name: "Validation Pipeline"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Download repository
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        name: Setup Python
      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
      - uses: hacs/action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY: integration
      - uses: home-assistant/actions/hassfest@master
        name: Hassfest